"""
Config Manager - Менеджер конфигурации (Python обертка для C++)
"""

import os
import json
from typing import Dict, List


class ConfigManager:
    """Менеджер конфигурации приложения"""
    
    def __init__(self):
        self.config_dir = self._get_config_dir()
        self.config_file = os.path.join(self.config_dir, "config.ini")
        self.locale_dir = os.path.join(self.config_dir, "locales")
        
        # Создаем директорию конфигурации
        self.create_config_dir()
    
    def _get_config_dir(self) -> str:
        """Получить директорию конфигурации"""
        if os.name == 'nt':  # Windows
            # Используем APPDATA или USERPROFILE
            appdata = os.environ.get('APPDATA')
            userprofile = os.environ.get('USERPROFILE')
            
            if appdata:
                return os.path.join(appdata, 'VitalSign')
            elif userprofile:
                return os.path.join(userprofile, 'AppData', 'Roaming', 'VitalSign')
            else:
                # Fallback на текущую директорию
                return '.VitalSign'
        else:  # Linux/Mac
            # Используем HOME
            home = os.path.expanduser("~")
            return os.path.join(home, ".VitalSign")
    
    def create_config_dir(self) -> bool:
        """Создать директорию конфигурации"""
        try:
            if not os.path.exists(self.config_dir):
                os.makedirs(self.config_dir)
                print(f"Config directory created: {self.config_dir}")
                return True
            else:
                print(f"Config directory already exists: {self.config_dir}")
                return True
        except Exception as e:
            print(f"Error creating config directory: {e}")
            return False
    
    def save_config(self, key: str, value: str) -> bool:
        """Сохранить конфигурацию"""
        try:
            configs = self.load_all_configs()
            configs[key] = value
            return self.save_all_configs(configs)
        except Exception as e:
            print(f"Error saving config: {e}")
            return False
    
    def load_config(self, key: str) -> str:
        """Загрузить конфигурацию"""
        try:
            configs = self.load_all_configs()
            return configs.get(key, "")
        except Exception as e:
            print(f"Error loading config: {e}")
            return ""
    
    def delete_config(self, key: str) -> bool:
        """Удалить конфигурацию"""
        try:
            configs = self.load_all_configs()
            if key in configs:
                del configs[key]
                return self.save_all_configs(configs)
            return False
        except Exception as e:
            print(f"Error deleting config: {e}")
            return False
    
    def load_all_configs(self) -> Dict[str, str]:
        """Загрузить все конфигурации"""
        configs = {}
        
        try:
            if not os.path.exists(self.config_file):
                return configs
            
            with open(self.config_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    
                    # Пропускаем комментарии и пустые строки
                    if not line or line.startswith('#') or line.startswith(';'):
                        continue
                    
                    # Парсим key=value
                    if '=' in line:
                        key, value = line.split('=', 1)
                        configs[key.strip()] = value.strip()
        
        except Exception as e:
            print(f"Error loading all configs: {e}")
        
        return configs
    
    def save_all_configs(self, configs: Dict[str, str]) -> bool:
        """Сохранить все конфигурации"""
        try:
            # Убеждаемся что директория существует
            if not os.path.exists(self.config_dir):
                os.makedirs(self.config_dir)
            
            with open(self.config_file, 'w', encoding='utf-8') as f:
                f.write("# VitalSign Configuration File\n")
                f.write("# Generated by VitalSign\n\n")
                
                for key, value in configs.items():
                    f.write(f"{key}={value}\n")
            
            return True
        except Exception as e:
            print(f"Error saving all configs: {e}")
            return False
    
    def clear_config(self) -> bool:
        """Очистить конфигурацию"""
        try:
            if os.path.exists(self.config_file):
                os.remove(self.config_file)
                return True
            return False
        except Exception as e:
            print(f"Error clearing config: {e}")
            return False
    
    def get_locale_path(self) -> str:
        """Получить путь к локализациям"""
        return self.locale_dir
    
    def save_locale_data(self, language: str, data: str) -> bool:
        """Сохранить данные локализации"""
        try:
            # Создаем директорию для локализаций
            if not os.path.exists(self.locale_dir):
                os.makedirs(self.locale_dir)
            
            locale_file = os.path.join(self.locale_dir, f"{language}.json")
            
            with open(locale_file, 'w', encoding='utf-8') as f:
                f.write(data)
            
            return True
        except Exception as e:
            print(f"Error saving locale data: {e}")
            return False
    
    def load_locale_data(self, language: str) -> str:
        """Загрузить данные локализации"""
        try:
            locale_file = os.path.join(self.locale_dir, f"{language}.json")
            
            if not os.path.exists(locale_file):
                return ""
            
            with open(locale_file, 'r', encoding='utf-8') as f:
                return f.read()
        
        except Exception as e:
            print(f"Error loading locale data: {e}")
            return ""
    
    def get_available_locales(self) -> List[str]:
        """Получить список доступных локализаций"""
        locales = []
        
        try:
            if not os.path.exists(self.locale_dir):
                return locales
            
            for filename in os.listdir(self.locale_dir):
                if filename.endswith('.json'):
                    locales.append(filename[:-5])  # Убираем .json
        
        except Exception as e:
            print(f"Error getting available locales: {e}")
        
        return locales
    
    def save_json_config(self, key: str, data: dict) -> bool:
        """Сохранить JSON конфигурацию"""
        try:
            json_data = json.dumps(data, ensure_ascii=False, indent=2)
            return self.save_config(key, json_data)
        except Exception as e:
            print(f"Error saving JSON config: {e}")
            return False
    
    def load_json_config(self, key: str) -> dict:
        """Загрузить JSON конфигурацию"""
        try:
            json_data = self.load_config(key)
            if json_data:
                return json.loads(json_data)
        except Exception as e:
            print(f"Error loading JSON config: {e}")
        return {}
